spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:16}
      minimum-idle: ${DB_POOL_MIN_IDLE:4}
      connection-timeout: 10000

  data:
    redis:
      url: ${REDIS_URL}
      connect-timeout: 2s
      timeout: 2s
