-- D12 거리두기 실시간 presence 상태
--
-- Redis 사용 시 location에는 좌표를 기록하지 않는다.
-- location 컬럼은 presence.store=postgis 폴백에서만 사용한다.
CREATE TABLE active_presence (
                                 session_id          BIGINT PRIMARY KEY
                                     REFERENCES walk_session(session_id)
                                         ON DELETE CASCADE,

                                 user_id             BIGINT NOT NULL
                                     REFERENCES app_user(user_id)
                                         ON DELETE CASCADE,

                                 mode                VARCHAR(10) NOT NULL,

                                 consented_at        TIMESTAMPTZ NOT NULL,

                                 accuracy_m          NUMERIC(5,1),

                                 heading_deg         NUMERIC(6,2),

                                 stationary          BOOLEAN NOT NULL DEFAULT false,

    -- Redis 장애 시 PostGIS 폴백에서만 사용한다.
    -- Redis가 기본 저장소일 때는 항상 NULL이다.
                                 location            GEOMETRY(Point, 4326),

                                 updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

                                 CONSTRAINT chk_active_presence_mode
                                     CHECK (mode IN ('off', 'distance', 'meet')),

                                 CONSTRAINT chk_active_presence_accuracy
                                     CHECK (
                                         accuracy_m IS NULL
                                             OR (accuracy_m >= 0 AND accuracy_m <= 9999.9)
                                         ),

                                 CONSTRAINT chk_active_presence_heading
                                     CHECK (
                                         heading_deg IS NULL
                                             OR (heading_deg >= 0 AND heading_deg < 360)
                                         )
);

CREATE INDEX idx_active_presence_updated
    ON active_presence(updated_at);

CREATE INDEX idx_active_presence_mode_updated
    ON active_presence(mode, updated_at);

CREATE INDEX idx_active_presence_location
    ON active_presence
    USING GIST(location)
    WHERE location IS NOT NULL;

COMMENT ON TABLE active_presence IS
    'D12 거리두기·만나보기 활성 세션 상태. 실시간 좌표는 Redis가 기본이며 location은 PostGIS 폴백 전용이다.';

COMMENT ON COLUMN active_presence.location IS
    'presence.store=postgis일 때만 사용하는 폴백 좌표. Redis 경로에서는 NULL을 유지한다.';

COMMENT ON COLUMN active_presence.consented_at IS
    '현재 산책 세션에서 위치정보 수집에 동의한 시각.';


-- 거리두기 접근 이벤트
--
-- 상대방 좌표, 실거리, 이름, 반려견 정보는 저장하지 않는다.
-- 접근 알림 이력과 쿨다운 판정에 필요한 가공 정보만 저장한다.
CREATE TABLE proximity_event (
                                 proximity_event_id      BIGINT GENERATED BY DEFAULT AS IDENTITY
                                     PRIMARY KEY,

                                 recipient_session_id    BIGINT NOT NULL
                                     REFERENCES walk_session(session_id)
                                         ON DELETE CASCADE,

                                 other_session_id        BIGINT NOT NULL
                                     REFERENCES walk_session(session_id)
                                         ON DELETE CASCADE,

                                 distance_band           VARCHAR(16) NOT NULL,

                                 bearing_octant          SMALLINT,

                                 bearing_spread          SMALLINT,

                                 trend                   VARCHAR(16) NOT NULL,

                                 first_detected_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

                                 last_notified_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

                                 notify_count            INTEGER NOT NULL DEFAULT 1,

                                 active                  BOOLEAN NOT NULL DEFAULT true,

                                 ended_at                TIMESTAMPTZ,

                                 CONSTRAINT chk_proximity_event_different_sessions
                                     CHECK (recipient_session_id <> other_session_id),

                                 CONSTRAINT chk_proximity_event_distance_band
                                     CHECK (
                                         distance_band IN (
                                                           'VERY_CLOSE',
                                                           'BAND_30_50',
                                                           'BAND_50_100'
                                             )
                                         ),

                                 CONSTRAINT chk_proximity_event_bearing_octant
                                     CHECK (
                                         bearing_octant IS NULL
                                             OR (bearing_octant >= 0 AND bearing_octant <= 7)
                                         ),

                                 CONSTRAINT chk_proximity_event_bearing_spread
                                     CHECK (
                                         bearing_spread IS NULL
                                             OR bearing_spread IN (45, 90)
                                         ),

                                 CONSTRAINT chk_proximity_event_bearing_pair
                                     CHECK (
                                         (bearing_octant IS NULL AND bearing_spread IS NULL)
                                             OR
                                         (bearing_octant IS NOT NULL AND bearing_spread IS NOT NULL)
                                         ),

                                 CONSTRAINT chk_proximity_event_very_close
                                     CHECK (
                                         distance_band <> 'VERY_CLOSE'
                                             OR (
                                             bearing_octant IS NULL
                                                 AND bearing_spread IS NULL
                                             )
                                         ),

                                 CONSTRAINT chk_proximity_event_trend
                                     CHECK (
                                         trend IN (
                                                   'NEW',
                                                   'APPROACHING',
                                                   'STEADY',
                                                   'LEAVING'
                                             )
                                         ),

                                 CONSTRAINT chk_proximity_event_notify_count
                                     CHECK (
                                         notify_count >= 1
                                             AND notify_count <= 5
                                         ),

                                 CONSTRAINT chk_proximity_event_end
                                     CHECK (
                                         (active = true AND ended_at IS NULL)
                                             OR
                                         (active = false AND ended_at IS NOT NULL)
                                         )
);

-- 동일한 수신 세션과 상대 세션 사이에는
-- 활성 접근 이벤트를 한 개만 허용한다.
CREATE UNIQUE INDEX uk_proximity_event_active_pair
    ON proximity_event(recipient_session_id, other_session_id)
    WHERE active = true;

CREATE INDEX idx_proximity_event_recipient_history
    ON proximity_event(recipient_session_id, last_notified_at DESC);

CREATE INDEX idx_proximity_event_other_session
    ON proximity_event(other_session_id);

COMMENT ON TABLE proximity_event IS
    '거리두기 접근 알림 이력. 좌표와 실거리는 저장하지 않고 거리 밴드·방향 구간·추세만 저장한다.';

COMMENT ON COLUMN proximity_event.other_session_id IS
    '서버 중복 알림 및 쿨다운 판정 전용 값이며 API 응답에는 노출하지 않는다.';