CREATE TABLE meet_profile (
    user_id             BIGINT PRIMARY KEY REFERENCES app_user(user_id) ON DELETE CASCADE,
    dog_name            VARCHAR(50) NOT NULL,
    breed               VARCHAR(80) NOT NULL,
    age_years           SMALLINT,
    profile_image_url   VARCHAR(500),
    temperament_tags    VARCHAR(30)[] NOT NULL DEFAULT '{}',
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_meet_profile_age CHECK (age_years IS NULL OR (age_years >= 0 AND age_years <= 40)),
    CONSTRAINT chk_meet_profile_tags CHECK (cardinality(temperament_tags) <= 8)
);

CREATE TABLE meet_request (
    request_id              UUID PRIMARY KEY,
    requester_session_id    BIGINT NOT NULL REFERENCES walk_session(session_id) ON DELETE CASCADE,
    recipient_session_id    BIGINT NOT NULL REFERENCES walk_session(session_id) ON DELETE CASCADE,
    requester_user_id       BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    recipient_user_id       BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    status                  VARCHAR(16) NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at              TIMESTAMPTZ NOT NULL,
    responded_at            TIMESTAMPTZ,
    ended_at                TIMESTAMPTZ,
    CONSTRAINT chk_meet_request_different_sessions CHECK (requester_session_id <> recipient_session_id),
    CONSTRAINT chk_meet_request_different_users CHECK (requester_user_id <> recipient_user_id),
    CONSTRAINT chk_meet_request_status CHECK (status IN ('PENDING','ACCEPTED','REJECTED','CANCELLED','EXPIRED','ENDED')),
    CONSTRAINT chk_meet_request_expiry CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX uk_meet_request_active_pair
    ON meet_request(
        LEAST(requester_session_id, recipient_session_id),
        GREATEST(requester_session_id, recipient_session_id)
    )
    WHERE status IN ('PENDING', 'ACCEPTED');

CREATE INDEX idx_meet_request_requester ON meet_request(requester_session_id, created_at DESC);
CREATE INDEX idx_meet_request_recipient ON meet_request(recipient_session_id, created_at DESC);

CREATE TABLE meet_block (
    blocker_user_id     BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    blocked_user_id     BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (blocker_user_id, blocked_user_id),
    CONSTRAINT chk_meet_block_self CHECK (blocker_user_id <> blocked_user_id)
);

CREATE TABLE meet_request_audit (
    audit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      UUID NOT NULL,
    actor_user_id   BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    event_type      VARCHAR(20) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_meet_audit_event CHECK (event_type IN ('REQUESTED','ACCEPTED','REJECTED','CANCELLED','EXPIRED','ENDED','BLOCKED'))
);

CREATE INDEX idx_meet_audit_request ON meet_request_audit(request_id, created_at);

COMMENT ON TABLE meet_request_audit IS '만나보기 상태 전이 감사 로그. 좌표와 거리 정보는 저장하지 않는다.';
