ALTER TABLE app_user
    ADD COLUMN profile_image_url TEXT,
    ADD COLUMN deleted_at TIMESTAMPTZ;

CREATE TABLE dog_profile (
    dog_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    name                VARCHAR(50) NOT NULL,
    breed               VARCHAR(80) NOT NULL,
    birth_date          DATE NOT NULL,
    profile_image_url   TEXT,
    temperament_tags    VARCHAR(30)[] NOT NULL DEFAULT '{}',
    is_default          BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT chk_dog_birth_date CHECK (birth_date <= CURRENT_DATE)
);

CREATE INDEX idx_dog_profile_user
    ON dog_profile(user_id, dog_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_dog_profile_default
    ON dog_profile(user_id)
    WHERE is_default = true AND deleted_at IS NULL;

CREATE TABLE notification_setting (
    user_id             BIGINT PRIMARY KEY REFERENCES app_user(user_id) ON DELETE CASCADE,
    service_enabled     BOOLEAN NOT NULL DEFAULT true,
    distance_enabled    BOOLEAN NOT NULL DEFAULT true,
    meet_enabled        BOOLEAN NOT NULL DEFAULT true,
    group_enabled       BOOLEAN NOT NULL DEFAULT true,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE walk_session_dog (
    session_id          BIGINT NOT NULL REFERENCES walk_session(session_id) ON DELETE CASCADE,
    dog_id              BIGINT NOT NULL REFERENCES dog_profile(dog_id),
    dog_name            VARCHAR(50) NOT NULL,
    breed               VARCHAR(80) NOT NULL,
    PRIMARY KEY (session_id, dog_id)
);

-- D13에서 이미 공개 프로필을 만든 개발 계정은 D14 반려견 목록으로 자연스럽게 이어준다.
INSERT INTO dog_profile(user_id, name, breed, birth_date, profile_image_url, temperament_tags, is_default)
SELECT profile.user_id,
       profile.dog_name,
       profile.breed,
       CURRENT_DATE - make_interval(years => COALESCE(profile.age_years, 0)),
       profile.profile_image_url,
       profile.temperament_tags,
       true
FROM meet_profile profile
WHERE NOT EXISTS (
    SELECT 1 FROM dog_profile dog WHERE dog.user_id = profile.user_id
);

INSERT INTO notification_setting(user_id)
SELECT user_id FROM app_user
ON CONFLICT (user_id) DO NOTHING;
