CREATE TABLE walk_group (
    group_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT NOT NULL REFERENCES app_user(user_id),
    name           VARCHAR(50) NOT NULL,
    description    VARCHAR(200) NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT chk_walk_group_name CHECK (length(trim(name)) > 0)
);

CREATE TABLE group_member (
    group_id   BIGINT NOT NULL REFERENCES walk_group(group_id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    role       VARCHAR(10) NOT NULL,
    joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT chk_group_member_role CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE UNIQUE INDEX uk_group_single_owner
    ON group_member(group_id)
    WHERE role = 'OWNER';

CREATE INDEX idx_group_member_user
    ON group_member(user_id, joined_at DESC);

CREATE TABLE group_invite (
    invite_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     BIGINT NOT NULL REFERENCES walk_group(group_id) ON DELETE CASCADE,
    invite_code  CHAR(6) NOT NULL UNIQUE,
    created_by   BIGINT NOT NULL REFERENCES app_user(user_id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,
    revoked_at   TIMESTAMPTZ,
    CONSTRAINT chk_group_invite_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_group_invite_group_active
    ON group_invite(group_id, expires_at DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE group_shared_course (
    shared_course_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id          BIGINT NOT NULL REFERENCES walk_group(group_id) ON DELETE CASCADE,
    shared_by_user_id BIGINT NOT NULL REFERENCES app_user(user_id),
    course_source     VARCHAR(10) NOT NULL,
    course_id         BIGINT NOT NULL,
    save_count        INTEGER NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_group_shared_course_source CHECK (course_source IN ('walk', 'custom')),
    CONSTRAINT chk_group_shared_course_save_count CHECK (save_count >= 0),
    CONSTRAINT uk_group_shared_course UNIQUE (group_id, course_source, course_id)
);

CREATE INDEX idx_group_shared_course_group_created
    ON group_shared_course(group_id, created_at DESC, shared_course_id DESC);

CREATE TABLE group_course_save (
    shared_course_id BIGINT NOT NULL REFERENCES group_shared_course(shared_course_id) ON DELETE CASCADE,
    user_id          BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    saved_course_id  BIGINT REFERENCES custom_course(custom_course_id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (shared_course_id, user_id)
);

CREATE TABLE group_activity (
    activity_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id      BIGINT NOT NULL REFERENCES walk_group(group_id) ON DELETE CASCADE,
    actor_user_id BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    activity_type VARCHAR(24) NOT NULL,
    subject       VARCHAR(100),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_group_activity_type CHECK (activity_type IN (
        'GROUP_CREATED', 'GROUP_UPDATED', 'MEMBER_JOINED', 'MEMBER_LEFT',
        'MEMBER_REMOVED', 'COURSE_SHARED', 'COURSE_UNSHARED', 'COURSE_SAVED'
    ))
);

CREATE INDEX idx_group_activity_group_cursor
    ON group_activity(group_id, activity_id DESC);

COMMENT ON TABLE walk_group IS '초대 기반 산책 코스 공유 그룹';
COMMENT ON TABLE group_shared_course IS '멤버 위치가 아닌 기존 사용자 코스 참조만 저장한다';
COMMENT ON TABLE group_activity IS 'GPS 좌표를 저장하지 않는 그룹 활동 피드';
