-- 유저 테이블
CREATE TABLE app_user (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email           VARCHAR(255) NOT NULL,
    nickname        VARCHAR(50) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(20) NOT NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_app_user_email
      UNIQUE (email),

    CONSTRAINT uk_app_user_nickname
      UNIQUE (nickname),

    CONSTRAINT uk_app_user_phone
      UNIQUE (phone_number)
);

-- 산책 전체 기록 저장 테이블
CREATE TABLE walk_session (
      session_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      user_id             BIGINT NOT NULL
          REFERENCES app_user(user_id),

      started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
      ended_at            TIMESTAMPTZ,

      mode                VARCHAR(10) NOT NULL DEFAULT 'off',

      distance_m          NUMERIC(8,1),
      duration_sec        INTEGER,

      track_geom          GEOMETRY(LineString, 5186),

      matched_segments    BIGINT[],

      is_loop             BOOLEAN,

      is_saved            BOOLEAN NOT NULL DEFAULT false,

      is_representative   BOOLEAN NOT NULL DEFAULT false,

      course_name         VARCHAR(100),

      CONSTRAINT chk_walk_session_mode
          CHECK (mode IN ('off', 'distance', 'meet')),

      CONSTRAINT chk_walk_session_time
          CHECK (
              ended_at IS NULL
                  OR ended_at >= started_at
              )
);


-- 사용자별 산책 기록 조회용 인덱스
CREATE INDEX idx_walk_session_user
    ON walk_session(user_id);


-- 산책 중 GPS 포인트 기록 테이블
CREATE TABLE walk_track_point (
    point_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id      BIGINT NOT NULL
    REFERENCES walk_session(session_id)
    ON DELETE CASCADE,

    recorded_at     TIMESTAMPTZ NOT NULL,

    -- 내부 거리/공간 연산용 좌표계 EPSG:5186
    location        GEOMETRY(Point, 5186) NOT NULL,

    accuracy_m      NUMERIC(5,1),

    CONSTRAINT chk_track_accuracy
    CHECK (
        accuracy_m IS NULL
        OR accuracy_m >= 0
    )
);


-- 특정 산책의 GPS 포인트를 시간 순으로 조회할 때 사용
CREATE INDEX idx_track_point_session_time
    ON walk_track_point(
            session_id,
            recorded_at
        );


-- GPS 위치 기반 공간 검색용 인덱스
CREATE INDEX idx_track_point_location
    ON walk_track_point
    USING GIST(location);