-- 도보 네트워크 구간
-- GIS data-pipeline에서 전처리 후 적재
CREATE TABLE route_segment (
    segment_id          BIGINT PRIMARY KEY,

    -- pgRouting에서 사용하는 시작/끝 노드
    source              BIGINT NOT NULL,
    target              BIGINT NOT NULL,

    -- 실제 도보 구간 형상
    -- 내부 거리/공간 연산 좌표계 EPSG:5186
    geom                GEOMETRY(LineString, 5186) NOT NULL,

    -- 구간 길이(m)
    length_m            NUMERIC(8,2) NOT NULL,

    -- 노면 재질
    surface_type        VARCHAR(20),

    -- Sky View Factor
    svf                 NUMERIC(4,3),

    -- 노면 물리 상수
    albedo              NUMERIC(4,3),
    emissivity          NUMERIC(4,3),
    ground_flux_ratio   NUMERIC(4,3),

    -- 가장 가까운 공원까지 거리(m)
    park_proximity_m    NUMERIC(7,1),

    -- 시간대별 가로수 그늘 비율
    tree_shade_ratio_09 NUMERIC(4,3),
    tree_shade_ratio_12 NUMERIC(4,3),
    tree_shade_ratio_15 NUMERIC(4,3),
    tree_shade_ratio_18 NUMERIC(4,3),

    -- 시간대별 건물 그늘 비율
    bldg_shade_ratio_09 NUMERIC(4,3),
    bldg_shade_ratio_12 NUMERIC(4,3),
    bldg_shade_ratio_15 NUMERIC(4,3),
    bldg_shade_ratio_18 NUMERIC(4,3),

    -- 건물 + 가로수 등을 반영한 최종 그늘 비율
    shade_ratio_09      NUMERIC(4,3),
    shade_ratio_12      NUMERIC(4,3),
    shade_ratio_15      NUMERIC(4,3),
    shade_ratio_18      NUMERIC(4,3),

    -- 그늘 등급
    shade_grade         CHAR(1) DEFAULT 'C',

    -- 온도 등급
    temp_grade          CHAR(1) DEFAULT 'C'
);


-- pgRouting source 노드 조회용
CREATE INDEX idx_route_segment_source
    ON route_segment(source);


-- pgRouting target 노드 조회용
CREATE INDEX idx_route_segment_target
    ON route_segment(target);


-- PostGIS 공간 검색용
CREATE INDEX idx_route_segment_geom
    ON route_segment
    USING GIST(geom);



-- 도보 구간 분석용 샘플 포인트
CREATE TABLE segment_sample_point (
    -- DB에서 자동 생성
    sample_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 어떤 도보 구간에 속한 분석점인지
    segment_id         BIGINT NOT NULL
    REFERENCES route_segment(segment_id)
    ON DELETE CASCADE,

    -- 해당 segment 안에서의 순서
    -- 예: 0, 1, 2, 3 ...
    seq                SMALLINT NOT NULL,

    -- 분석점 위치
    -- EPSG:5186
    geom               GEOMETRY(Point, 5186) NOT NULL,

    -- 해당 지점의 Sky View Factor
    svf                NUMERIC(4,3),

    -- 노면 물리 상수
    albedo             NUMERIC(4,3),
    emissivity         NUMERIC(4,3),
    ground_flux_ratio  NUMERIC(4,3),

    -- 시간대별 그늘 여부
    is_shaded_09       BOOLEAN,
    is_shaded_12       BOOLEAN,
    is_shaded_15       BOOLEAN,
    is_shaded_18       BOOLEAN,

    -- 시간대별 그늘 원인
    -- 예: B = Building, T = Tree 등
    shade_src_09       CHAR(1),
    shade_src_12       CHAR(1),
    shade_src_15       CHAR(1),
    shade_src_18       CHAR(1),

    -- 한 segment 안에서 같은 seq가 중복 생성되는 것을 방지
    UNIQUE(segment_id, seq)
);


-- 특정 segment의 샘플 포인트를 순서대로 조회할 때 사용
CREATE INDEX idx_sample_segment
    ON segment_sample_point(
                            segment_id,
                            seq
        );


-- 샘플 포인트 공간 검색용
CREATE INDEX idx_sample_geom
    ON segment_sample_point
    USING GIST(geom);