CREATE TABLE custom_course (
    custom_course_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    course_name               VARCHAR(100) NOT NULL,
    waypoints                 JSONB NOT NULL,
    segment_ids               BIGINT[] NOT NULL,
    geom                      GEOMETRY(Geometry, 5186) NOT NULL,
    length_m                  NUMERIC(10,2) NOT NULL,
    duration_min              INTEGER NOT NULL,
    shade_ratio               NUMERIC(4,3) NOT NULL,
    estimated_surface_temp_c  NUMERIC(5,2) NOT NULL,
    reference_hour            SMALLINT NOT NULL,
    thermal_weather_date      DATE NOT NULL,
    thermal_model_confidence  VARCHAR(10) NOT NULL,
    is_loop                   BOOLEAN NOT NULL DEFAULT false,
    is_representative         BOOLEAN NOT NULL DEFAULT false,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_custom_course_name CHECK (length(trim(course_name)) > 0),
    CONSTRAINT chk_custom_course_waypoints CHECK (
        jsonb_typeof(waypoints) = 'array' AND jsonb_array_length(waypoints) >= 2
    ),
    CONSTRAINT chk_custom_course_segments CHECK (cardinality(segment_ids) >= 1),
    CONSTRAINT chk_custom_course_length CHECK (length_m > 0 AND length_m <= 50000),
    CONSTRAINT chk_custom_course_duration CHECK (duration_min > 0),
    CONSTRAINT chk_custom_course_shade CHECK (shade_ratio BETWEEN 0 AND 1),
    CONSTRAINT chk_custom_course_reference_hour CHECK (reference_hour IN (9, 12, 15, 18)),
    CONSTRAINT chk_custom_course_confidence CHECK (
        thermal_model_confidence IN ('LOW', 'MEDIUM', 'HIGH')
    )
);

CREATE INDEX idx_custom_course_user_created
    ON custom_course(user_id, created_at DESC);

CREATE INDEX idx_custom_course_geom
    ON custom_course USING GIST(geom);

CREATE UNIQUE INDEX uk_custom_course_one_representative_per_user
    ON custom_course(user_id)
    WHERE is_representative = true;

CREATE VIEW v_course AS
SELECT
    'walk'::varchar(10) AS course_source,
    session_id AS course_id,
    user_id,
    course_name,
    distance_m::numeric(10,2) AS length_m,
    CEIL(duration_sec / 60.0)::integer AS duration_min,
    matched_segments AS segment_ids,
    track_geom::geometry AS geom,
    is_loop,
    is_representative,
    started_at AS created_at
FROM walk_session
WHERE is_saved = true
  AND ended_at IS NOT NULL

UNION ALL

SELECT
    'custom'::varchar(10) AS course_source,
    custom_course_id AS course_id,
    user_id,
    course_name,
    length_m,
    duration_min,
    segment_ids,
    geom,
    is_loop,
    is_representative,
    created_at
FROM custom_course;

COMMENT ON TABLE custom_course IS
    '사용자가 지도에서 찍은 원본 지점과 보행망에 연결된 링크 순서를 함께 보존하는 직접 그리기 코스';

COMMENT ON VIEW v_course IS
    '기록 산책과 직접 그린 코스를 course_source + course_id로 통합 조회하는 뷰';
